// @gurt/visualizations — Observable Plot + D3 Komponenten.
// Jede Komponente liefert einen barrierefreien Tabellen-Fallback (siehe docs/06).
export { DataTable } from './components/data-table';
export type { DataTableProps } from './components/data-table';
export { ObservablePlot } from './components/observable-plot';
export { BarChart } from './components/bar-chart';
export type { BarChartProps } from './components/bar-chart';
export { LineChart } from './components/line-chart';
export type { LineChartProps } from './components/line-chart';
export { AreaChart } from './components/area-chart';
export type { AreaChartProps } from './components/area-chart';
export { BeeswarmChart } from './components/beeswarm-chart';
export type { BeeswarmChartProps } from './components/beeswarm-chart';
export { WaffleChart } from './components/waffle-chart';
export type { WaffleChartProps } from './components/waffle-chart';
export { allocateWaffle } from './components/waffle';
export type { WaffleSlice } from './components/waffle';
export { TreemapChart } from './components/treemap-chart';
export type { TreemapChartProps } from './components/treemap-chart';
export { layoutTreemap, toTreemapItems } from './components/treemap';
export type { TreemapItem, TreemapRect } from './components/treemap';
export { SankeyChart } from './components/sankey-chart';
export type { SankeyChartProps } from './components/sankey-chart';
export { layoutSankey, toSankeyLinks } from './components/sankey';
export type { SankeyLink, SankeyNode, SankeyComputedLink, SankeyLayout } from './components/sankey';
export { RatioArray } from './components/ratio-array-chart';
export type { RatioArrayProps } from './components/ratio-array-chart';
export { toRatioPanels } from './components/ratio-array';
export type { RatioPanel } from './components/ratio-array';
export { SignaturePoster } from './components/signature-poster';
export type { SignaturePosterProps, SignatureSegment } from './components/signature-poster';
export { PositionMatrix } from './components/position-matrix';
export type { PositionMatrixProps } from './components/position-matrix';
export { buildMatrix, haltungStyle } from './components/matrix';
export type { Haltung, Matrix, MatrixPosition } from './components/matrix';
export type { Cell, Column, Row } from './lib/types';
